# Generated by Django 4.0.3 on 2022-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField()),
                ('Product_art', models.CharField(max_length=1000)),
                ('Product_name', models.CharField(max_length=1000)),
                ('Product_price', models.CharField(max_length=1000)),
                ('Product_brand', models.CharField(max_length=1000)),
                ('Product_category', models.CharField(max_length=1000)),
                ('Product_origin_link', models.CharField(max_length=1000)),
                ('Product_description', models.TextField()),
            ],
        ),
    ]
