# Generated by Django 4.0.3 on 2022-05-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_id',
        ),
    ]
